email: "randolphl@uthscsa.edu"

search:
  database: "gds"
  retmax: 500
  reldate: 365   # last N days

  query: >
    (bronchopulmonary dysplasia OR BPD) AND
    (RNA-seq OR RNAseq OR microarray OR "gene expression profiling") AND
    (Homo sapiens[Organism]) AND
    (neonate OR newborn OR infant OR preterm)
